# Utiliser une image Python comme base
FROM python:3.11-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les dépendances nécessaires
COPY requirements.txt /requirements.txt

# Installer les dépendances
RUN pip install --no-cache-dir -r /requirements.txt

# Copier tout le code source dans le conteneur
COPY . .

# Exposer le port pour FastAPI
EXPOSE 8282

# Commande pour exécuter l'application FastAPI
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8282"]
