version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_api
    container_name: fastapi-container
    networks:
      - my_network
    ports:
      - "8181:8181" # Port exposé pour FastAPI

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile_streamlit
    container_name: streamlit-container
    networks:
      - my_network
    ports:
      - "8501:8501" # Port exposé pour Streamlit

networks:
  my_network:
    driver: bridge
