# Use official Python image as the base image
FROM python:3.11

# Set the environment variable for unbuffered output (useful for logging)
ENV PYTHONUNBUFFERED=True

# Copy requirements.txt to the container and install dependencies
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Copy the entire app code to the container
COPY . .

# Set the entry point to run the FastAPI app with Uvicorn
ENTRYPOINT ["sh", "-c", "uvicorn api:app --host=0.0.0.0 --port=$PORT"]

# Default to port 8181 if not specified
ENV PORT 8181

# Expose the port (default is 8181)
EXPOSE 8181
