# Use the official Streamlit base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .
EXPOSE 8181

# Command to run the Streamlit app
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8181"]